# Generated by Django 4.1.2 on 2022-11-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
