# Generated by Django 4.1.2 on 2022-11-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_valor_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
