# Generated by Django 4.1.2 on 2022-11-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='valor',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='valor',
            new_name='value',
        ),
    ]
